### PR TITLE
add Decentralization 2.0

### LINKED ISSUE #85: Issue 03 - Add Decentralization 2.0 to News
# Request for content

_Be sure to check out the [Guide for submitting a new Issue](https://monthly.aragon.one/guides/guide_for_submitting_a_new_issue/) for submitting a new request_

### Request type:
_News_

### Description of the requested content
https://medium.com/@jtiannelli63/decentralization-2-0-2e47b263e0f2

### Additional information
Tag: DAOs

#### Deadline
By the end of the month, in time for Aragon Monthly issue 03 

- [x] I would like to have a bounty on this Issue that I will fund myself

### PR DESCRIPTION
**Pull request by bling5630**
# New content for Aragon 

**Closing of a referenced Issue**

Closes #85 

**Content category**

News

**Content type:**

Article

**Title**

Decentralization 2.0

**Description**

A plan of action for moving past the buzzwords.

### CODE REVIEW

**Comment by bling5630** [comment]
hello @john-light 

yes, I will add some of the text from the piece as a synopsis after the title,

thanks for your comment,

Tamas

**Comment by john-light** [comment]
The formatting needs fixed. Compare this entry to the others, there is extraneous/ redundant information in this entry. Also, the tag should be "DAOs" and the tag should link to daos.md not tag.md.

**Comment by bling5630** [comment]
dear @john-light
somehow, I can't submit the pull request separately, however, I finalized several issues. Also as you can see up all of my PR navigate here, can you help me out?
thanks,
Tamas

**Comment by john-light** [comment]
@bling5630 thank you for making those changes! Just two more small things before I can approve the PR. 

1. The brief synopsis needs to move down a few sections so it is between the "author" and "Read more" sections.

2. There should be a link to the "no image" file that we have in the repo where the image would normally go. As the [Guide for submitting News](https://monthly.aragon.one/guides/guide_for_submitting_news/) states "Entries without an image should have the monthly_no_image.png used".

**Comment by Smokyish** [comment]
As there is another PR for the same issue, closing this one.

**Pull request closed without merging**
