### PR TITLE
Create Dgov18.md

### LINKED ISSUE #189: Information on dGov.Earth event in Athens, Greece, Dec. 7-9, on multidisciplinary take on distributed governance.
# Request for content

_Be sure to check out the [Guide for submitting a new Issue](https://monthly.aragon.one/guides/guide_for_submitting_a_new_issue/) for submitting a new request_

### Request type:
_News_

#### Content type:
_Informative_

### Description of the requested content
I would like to read about the event that is happening on inter/multi-disciplinary distributed governance initiatives to unite the grassroots of society and focus on the use of distributed governance for common good and common betterment, poly-win, sustainable approach to governance and the global operating system. 

### Additional information
Minimum 500 words, maximum 1500 words

#### Deadline
By the end of the month, in time for Aragon Monthly issue #X

### PR DESCRIPTION
**Pull request by jgmhooks**
# New content for Aragon Monthly

_Be sure to check out the [Guide for submitting a new Pull Request](https://monthly.aragon.one/guides/guide_for_submitting_a_new_pull_request/) before submitting your PR_

### Closing of a referenced Issue
Closes #189 

### Content category
_News_ 

#### Content type:
_Opinion Piece_ 

### Title
dGov.Earth Interdisciplinary Distributed Governance Conference

### Description
Information on the interdisciplinary conference on distributed governance happening in Greece at the end of the year, Dec. 7-9, Athens, Greece.
Organized by 4 Germans, 1 Slovenian, 1 Ukranian, and 1 Brazilian.

### CODE REVIEW

**Comment by john-light** [comment]
This PR is out of date now that the conference has been postponed: https://medium.com/dgov/distributed-governance-conference-athens-postponed-9501c97ec7e0

**Comment by Smokyish** [comment]
Closing this for now as the submitter hasn't responded to request for changes and as commented above, isn't currently up to date.

**Comment by Smokyish** [comment]
Closing this for now as the submitter hasn't responded to request for changes and as commented above, isn't currently up to date.

**Comment by Smokyish** [comment]
Closing this for now as the submitter hasn't responded to request for changes and as commented above, isn't currently up to date.

**Comment by Smokyish** [comment]
As the submitter @jgmhooks isn't replying to requests for change and as commented above, this is now very outdated, closing the PR.

**Comment by Smokyish** [comment]
Closing this as there has been no response to the request for changes and as commented above, this is now outdated.

**Pull request closed without merging**
