### PR TITLE
aragon-monthly/news/issue03/#94

### LINKED ISSUE #94: Issue 04 - Add "Pilot Experiment of the Space Decentral Collaboration Process" to News
### Request type:
_News_

### Description of the requested content
https://blog.space.coop/pilot-experiment-of-the-space-decentral-collaboration-process-8d2b9bfe4aa2

### Additional information
Tag: DAOs

#### Deadline
By the end of the month, in time for Aragon Monthly issue 03

- [x] I would like to have a bounty on this Issue that I will fund myself

### PR DESCRIPTION
**Pull request by debragail**
# New content for Aragon Monthly

### Closing of a referenced Issue
Closes #94 

### Content category
_News_

#### Content type:
 _Column_

### Title
Pilot Experiment of the Space Decentral Collaboration Process

### Description

https://blog.space.coop/pilot-experiment-of-the-space-decentral-collaboration-process-8d2b9bfe4aa2

### CODE REVIEW

**Comment by debragail** [comment]
screen shot 2018-05-07 at 22 05 31

**Comment by debragail** [comment]
I signed the CLA

**Comment by debragail** [comment]
screen shot 2018-05-09 at 14 44 50
I've signed the CLA and I don't know why it's not syncing my email address.

**Comment by Smokyish** [comment]
This is a real mess @debragail.

> debragail wants to merge 123 commits into aragon:master from debragail:aragon-monthly/news/issue03/#94

And [84 files changed](https://github.com/aragon/aragon-monthly/pull/109/files).

As this is so far from a proper submission, closing the PR.

**Comment by debragail** [comment]
The page looks good to me and the CLA Assistant still doesn’t work.

**Comment by debragail** [comment]
You’re not addressing the CLA Assistant problem?

**Comment by Smokyish** [comment]
@debragail Hi, i've forgotten to reply to your comments here, what kind of issue did you have with the CLA? Haven't heard of any trouble from others with it so details would be much appreciated. Do you perhaps have a browser extension/plugin that might affect the behaviour of signing the CLA?

This Pull Request had a huge issue of making a lot of unnecessary changes and it seemed like making a fresh PR that is rebased against the `master` branch would be easier than making changes to this one, unfortunately i did forget to mention this in the previous comment.

If you might still be interested in contributing to Monthly, may i suggest taking a look at this bigger new bounty we currently have active for compiling a full issue at https://github.com/aragon/aragon-monthly/issues/111

**Comment by debragail** [comment]
@Smokyish those commits were not from me.  I'm looking at #111 but still have the CLA issue.  I created a new PR for this issue:

https://github.com/aragon/aragon-monthly/pull/131

**Comment by debragail** [comment]
@Smokyish since this was integrated into the site can I claim the bounty on this?

**Pull request closed without merging**
