### PR TITLE
Update index.md

### LINKED ISSUE #30: Issue 02 - Add Bringing DAOs back — Aragon Monthly to News
# Request for content

### Request type:
_News_

### Description of the requested content
Add Bringing DAOs back — Aragon Monthly, https://blog.aragon.one/bringing-daos-back-aragon-monthly-92756cb65639 to News.

### Additional information
Tag: Aragon

#### Deadline
By the end of the month, in time for Aragon Monthly issue 02

### PR DESCRIPTION
**Pull request by djbohr13**
# New content for Aragon Monthly

_Be sure to check out the [Guide for submitting a new Pull Request](https://monthly.aragon.one/guides/guide_for_submitting_a_new_pull_request/) before submitting your PR_

### Closing of a referenced Issue
Closes #30 

### Content category
Issue 02: News: Aragon

#### Content type:
Bringing Daos back news story added

### CODE REVIEW

**Comment by Smokyish** [comment]
Thanks @ludmila-omlopes!

**Comment by Bradymck** [comment]
@Smokyish Would you prefer we approve or just comment?

**Comment by Smokyish** [comment]
@Bradymck If you think it looks all good, please do approve, easier to track if something should be merged or not.

**Comment by Bradymck** [comment]
@Smokyish will do, thanks. FYI, I'm really liking the model you're developing here as a basic framework for any project. I have been linking back to this repository for our community to move forward with their proposals before our developer tools (d0xINFRA) and Aragon are on mainnet. I feel like this model could be boiled down to get any of [our proposals](https://github.com/district0x/district-proposals/issues) moving today in a very realistic way. 

I guess in short, I'm saying thanks. Bootstrapping DAOs one pull request/bounty at a time, you sir have my respect. 🖖

**Comment by ludmila-omlopes** [comment]
Totally agree with @Bradymck ! And also I like a lot how Aragon is always supporting other projects like hiring through Ethlance, integrating Status' bounty service here with the tags... that's one of the most important things for growing the community together, and Tatu nails it =)

**Comment by djbohr13** [comment]
@Smokyish any idea when the 1st 3 bounties i did for issue 01 will get paid? i know this one is bounty-less, just curious.

**Comment by Smokyish** [comment]
@djbohr13 Yes, I have been discussing things related to the Status Open Bounty system with them, and now know for example, that we can not close multiple Issues in a single Pull Request, so that's why some of your and @roundminer bounties aren't showing up in the SOB app. Now that we know this, we can avoid the problem in the future, but it will likely be easier to manually reward you the missing bounties for these past ones.

And the manual payout confirmations we try to make at least weekly to get them rewarded to people.

**Comment by Smokyish** [comment]
And thank you very much for the kind words @Bradymck & @ludmila-omlopes, very happy to hear that you have found this useful and helpful. Let's keep refining and working on making this better together!

**Comment by djbohr13** [comment]
Awesome. Thanks a bunch 😎

**Pull request merged**
