### PR TITLE
Submission for #153 issue 6: freeform article on governance.

### LINKED ISSUE #153: Issue 06 - Article: Freeform article about governance
# Request for content

### Request type:
Article

#### Content type:
Opinion piece

### Description of the requested content
Thoughtful, freeform article on the subject `governance`. You have the freedom to write an editorial piece of your choosing.

**Article must be original content created for this purpose and not published anywhere before this**.

> An opinion piece is an article that mainly reflects the author's opinion about the subject. Opinion pieces in the newspaper are often written by a subject-matter expert, a person with a unique perspective on an issue.

### Additional information
Minimum 1500 words, maximum 2500 words

#### Deadline
By the end of June, in time for Aragon Monthly issue 06
___
## Notes

We will allow for a **maximum of 3 revisions** to the Pull Request based on feedback given by the Monthly staff, if the PR still doesn't meet the quality and standard, we will close the PR.

This issue **should be finished and merged as soon as possible**, this is first-come, first-served; the first proper Pull Request will be merged and will be awarded the associated bounty.

### PR DESCRIPTION
**Pull request by ThijsMaasLaw**
Open to feedback.  First time Github - im not a 100% sure I submitted this properly.

# New content for Aragon Monthly

_Be sure to check out the [Guide for submitting a new Pull Request](https://monthly.aragon.one/guides/guide_for_submitting_a_new_pull_request/) before submitting your PR_

### Closing of a referenced Issue
Closes #153  

### Content category
_Article_ 

#### Content type:
_Opinion Piece_ 

### Title
Governance through code: the biggest evolution in governance since the company.

### Description
Just over 2500 words article on the history and importance of governance to emphasize the importance of experiments in code-based governance. 

[Issue 6 article submission - Governance through code.docx](https://github.com/aragon/aragon-monthly/files/2097658/Issue.6.article.submission.-.Governance.through.code.docx)

### CODE REVIEW

**Comment by ThijsMaasLaw** [comment]
Please ignore the highlights and comments, I forgot to delete them.

**Comment by Smokyish** [comment]
@ThijsMaasLaw Thank you for the submission, we will let you know of any requested changes after review(s) are done!

**Comment by Smokyish** [comment]
@ThijsMaasLaw First thing i noticed is the binary form of the submission, it is a `.docx` document, the submission should be in [MarkDown](https://en.wikipedia.org/wiki/Markdown) format, which are `.md` files.

You could try putting the text through a converter like http://markitdown.medusis.com/ or https://euangoddard.github.io/clipboard2markdown/ and then checking with http://markdownlivepreview.com for finishing touches.

Don't hesitate to ask if there's anything we can help with!

**Comment by ThijsMaasLaw** [comment]
@Smokyish Uploaded the .md and followed your style-guide. Can you find the document like this and, if so, should I just delete the other document?

**Comment by Smokyish** [comment]
@ThijsMaasLaw Hi, the md file looks okay, will leave it for reviewers to check it before merging. 

You can safely delete the .docx file from the Pull Request.

And I would recommend taking a look at our [How to claim an Aragon bounty using Status Open Bounty](https://wiki.aragon.one/tutorials/Status_Open_Bounty_Guide/) guide.

**Comment by ThijsMaasLaw** [comment]
No clue if this is how you're supposed to do this, but I created a branch ('new branch') to delete the file and submitted a new pull request. Man do I feel like a newby here on Github.

**Comment by Smokyish** [comment]
Closing this as a duplicate to #156

**Pull request closed without merging**
